from __future__ import annotations

from math import asin, cos, hypot, pi, sin, tan
from pathlib import Path


def write_extruded_polygon_mesh(path: Path, *, points: list[tuple[float, float]], half_length: float) -> None:
    top = [(x, y, half_length) for x, y in points]
    bottom = [(x, y, -half_length) for x, y in points]
    vertices = top + bottom
    vertex_count = len(points)
    faces: list[tuple[int, int, int]] = []

    for index in range(1, vertex_count - 1):
        faces.append((1, index + 1, index + 2))
        faces.append((vertex_count + 1, vertex_count + index + 2, vertex_count + index + 1))
    for index in range(vertex_count):
        next_index = (index + 1) % vertex_count
        top_a = index + 1
        top_b = next_index + 1
        bottom_a = vertex_count + index + 1
        bottom_b = vertex_count + next_index + 1
        faces.append((top_a, top_b, bottom_b))
        faces.append((top_a, bottom_b, bottom_a))

    lines = ["# Generated by scripts/generate_true_fixture_mesh_assets.py"]
    for vertex in vertices:
        lines.append("v {:.8f} {:.8f} {:.8f}".format(*vertex))
    for face in faces:
        lines.append("f {} {} {}".format(*face))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_ring_mesh(
    path: Path,
    *,
    inner_points: list[tuple[float, float]],
    outer_points: list[tuple[float, float]],
    half_height: float,
) -> None:
    if len(inner_points) != len(outer_points):
        raise ValueError("inner and outer rings must have the same point count")
    if len(inner_points) < 3:
        raise ValueError("ring mesh requires at least three points")

    count = len(inner_points)
    vertices = (
        [(x, y, half_height) for x, y in outer_points]
        + [(x, y, half_height) for x, y in inner_points]
        + [(x, y, -half_height) for x, y in outer_points]
        + [(x, y, -half_height) for x, y in inner_points]
    )

    def outer_top(index: int) -> int:
        return index + 1

    def inner_top(index: int) -> int:
        return count + index + 1

    def outer_bottom(index: int) -> int:
        return 2 * count + index + 1

    def inner_bottom(index: int) -> int:
        return 3 * count + index + 1

    faces: list[tuple[int, int, int]] = []
    for index in range(count):
        next_index = (index + 1) % count
        faces.extend(
            [
                (outer_top(index), outer_top(next_index), inner_top(next_index)),
                (outer_top(index), inner_top(next_index), inner_top(index)),
                (outer_bottom(index), inner_bottom(next_index), outer_bottom(next_index)),
                (outer_bottom(index), inner_bottom(index), inner_bottom(next_index)),
                (outer_top(index), outer_bottom(next_index), outer_top(next_index)),
                (outer_top(index), outer_bottom(index), outer_bottom(next_index)),
                (inner_top(index), inner_top(next_index), inner_bottom(next_index)),
                (inner_top(index), inner_bottom(next_index), inner_bottom(index)),
            ]
        )

    lines = ["# Generated by scripts/generate_true_fixture_mesh_assets.py"]
    for vertex in vertices:
        lines.append("v {:.8f} {:.8f} {:.8f}".format(*vertex))
    for face in faces:
        lines.append("f {} {} {}".format(*face))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_prism_mesh(path: Path, *, side_length: float, miter_extension: float, thickness: float, half_height: float) -> None:
    """Write a convex mitered wall prism mesh.

    Local +x is along the hole edge. Local +y points outward from the hole.
    The inner face is the exact hole boundary; only the outer face is extended
    for mitered visual/collision closure.
    """

    half_inner = 0.5 * side_length
    half_outer = half_inner + miter_extension
    vertices = [
        (-half_inner, 0.0, -half_height),
        (half_inner, 0.0, -half_height),
        (half_outer, thickness, -half_height),
        (-half_outer, thickness, -half_height),
        (-half_inner, 0.0, half_height),
        (half_inner, 0.0, half_height),
        (half_outer, thickness, half_height),
        (-half_outer, thickness, half_height),
    ]
    faces = [
        (1, 2, 3),
        (1, 3, 4),
        (5, 8, 7),
        (5, 7, 6),
        (1, 5, 6),
        (1, 6, 2),
        (2, 6, 7),
        (2, 7, 3),
        (3, 7, 8),
        (3, 8, 4),
        (4, 8, 5),
        (4, 5, 1),
    ]
    lines = ["# Generated by scripts/generate_true_fixture_mesh_assets.py"]
    for vertex in vertices:
        lines.append("v {:.8f} {:.8f} {:.8f}".format(*vertex))
    for face in faces:
        lines.append("f {} {} {}".format(*face))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def regular_polygon_side_length(*, apothem: float, sides: int) -> float:
    return 2.0 * apothem * tan(pi / sides)


def regular_polygon_points(*, apothem: float, sides: int) -> list[tuple[float, float]]:
    radius = float(apothem) / cos(pi / float(sides))
    points: list[tuple[float, float]] = []
    for index in range(sides):
        angle = 0.5 * pi + pi / float(sides) + 2.0 * pi * index / float(sides)
        points.append((radius * cos(angle), radius * sin(angle)))
    return points


def scaled_points(points: list[tuple[float, float]], scale: float) -> list[tuple[float, float]]:
    return [(x * scale, y * scale) for x, y in points]


def write_vertical_edge_highlight_mesh(
    path: Path,
    *,
    points: list[tuple[float, float]],
    half_length: float,
    radial_offset: float,
    tangent_half_width: float,
    radial_half_width: float,
) -> None:
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []
    local_faces = [
        (1, 2, 3),
        (1, 3, 4),
        (5, 7, 6),
        (5, 8, 7),
        (1, 5, 6),
        (1, 6, 2),
        (2, 6, 7),
        (2, 7, 3),
        (3, 7, 8),
        (3, 8, 4),
        (4, 8, 5),
        (4, 5, 1),
    ]
    for x, y in points:
        length = hypot(x, y)
        if length <= 1e-9:
            continue
        radial = (x / length, y / length)
        tangent = (-radial[1], radial[0])
        center = (x + radial_offset * radial[0], y + radial_offset * radial[1])
        corners = [
            (
                center[0] + tangent_half_width * tangent[0] + radial_half_width * radial[0],
                center[1] + tangent_half_width * tangent[1] + radial_half_width * radial[1],
            ),
            (
                center[0] - tangent_half_width * tangent[0] + radial_half_width * radial[0],
                center[1] - tangent_half_width * tangent[1] + radial_half_width * radial[1],
            ),
            (
                center[0] - tangent_half_width * tangent[0] - radial_half_width * radial[0],
                center[1] - tangent_half_width * tangent[1] - radial_half_width * radial[1],
            ),
            (
                center[0] + tangent_half_width * tangent[0] - radial_half_width * radial[0],
                center[1] + tangent_half_width * tangent[1] - radial_half_width * radial[1],
            ),
        ]
        base = len(vertices)
        vertices.extend([(cx, cy, half_length) for cx, cy in corners])
        vertices.extend([(cx, cy, -half_length) for cx, cy in corners])
        faces.extend(tuple(base + index for index in face) for face in local_faces)

    lines = ["# Generated by scripts/generate_true_fixture_mesh_assets.py"]
    for vertex in vertices:
        lines.append("v {:.8f} {:.8f} {:.8f}".format(*vertex))
    for face in faces:
        lines.append("f {} {} {}".format(*face))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def stadium_points(*, half_x: float, radius: float, arc_segments_per_end: int) -> list[tuple[float, float]]:
    straight_half = half_x - radius
    if straight_half <= 0.0:
        raise ValueError("stadium half_x must be larger than radius")

    points: list[tuple[float, float]] = []
    points.append((straight_half, radius))
    points.append((-straight_half, radius))
    for index in range(1, arc_segments_per_end + 1):
        angle = 0.5 * pi + pi * index / float(arc_segments_per_end)
        points.append((-straight_half + radius * cos(angle), radius * sin(angle)))
    points.append((straight_half, -radius))
    for index in range(1, arc_segments_per_end):
        angle = 1.5 * pi + pi * index / float(arc_segments_per_end)
        points.append((straight_half + radius * cos(angle), radius * sin(angle)))
    return points


def keyhole_points(
    *,
    radius: float,
    tab_half_width: float,
    tab_length: float,
    arc_segments: int,
) -> list[tuple[float, float]]:
    if radius <= 0.0:
        raise ValueError("keyhole radius must be positive")
    if tab_half_width <= 0.0 or tab_half_width >= radius:
        raise ValueError("keyhole tab half-width must be positive and smaller than radius")
    if tab_length <= 0.0:
        raise ValueError("keyhole tab length must be positive")
    if arc_segments < 2:
        raise ValueError("keyhole arc requires at least two segments")

    theta = float(asin(max(-1.0, min(1.0, tab_half_width / radius))))
    x_join = (radius * radius - tab_half_width * tab_half_width) ** 0.5
    front_x = radius + tab_length
    points: list[tuple[float, float]] = [
        (front_x, tab_half_width),
        (x_join, tab_half_width),
    ]
    arc_span = 2.0 * pi - 2.0 * theta
    for index in range(1, arc_segments):
        angle = theta + arc_span * index / float(arc_segments)
        points.append((radius * cos(angle), radius * sin(angle)))
    points.extend(
        [
            (x_join, -tab_half_width),
            (front_x, -tab_half_width),
        ]
    )
    return points


def main() -> None:
    output_dir = Path("assets/ur5e_full/assets")
    output_dir.mkdir(parents=True, exist_ok=True)

    wall_thickness = 0.012
    half_height = 0.026
    hex_apothem = 0.016
    triangle_apothem = 0.012
    peg_radius = 0.012
    peg_hex_apothem = peg_radius * cos(pi / 6.0)
    peg_triangle_apothem = peg_radius * cos(pi / 3.0)
    slot_radius = 0.016
    slot_half_x = slot_radius * 2.2
    slot_arc_segments_per_end = 3
    slot_arc_delta = pi / float(slot_arc_segments_per_end)
    keyhole_hole_radius = 0.016
    keyhole_hole_tab_half_width = 0.008
    keyhole_hole_tab_length = 0.009
    keyhole_peg_radius = 0.012
    keyhole_peg_tab_half_width = 0.005
    keyhole_peg_tab_length = 0.0065
    keyhole_arc_segments = 8
    tight_yaw_square_clearance = 0.00075
    tight_yaw_hex_clearance = 0.00050
    tight_yaw_triangle_clearance = 0.00075
    tight_yaw_keyhole_clearance = 0.00100
    tight_yaw_hex_apothem = peg_hex_apothem + tight_yaw_hex_clearance
    tight_yaw_triangle_apothem = peg_triangle_apothem + tight_yaw_triangle_clearance
    tight_yaw_keyhole_hole_radius = keyhole_peg_radius + tight_yaw_keyhole_clearance
    tight_yaw_keyhole_hole_tab_half_width = (
        keyhole_peg_tab_half_width + tight_yaw_keyhole_clearance
    )
    tight_yaw_keyhole_hole_tab_length = keyhole_peg_tab_length + tight_yaw_keyhole_clearance
    keyhole_theta = asin(
        max(-1.0, min(1.0, keyhole_hole_tab_half_width / keyhole_hole_radius))
    )
    keyhole_arc_delta = (2.0 * pi - 2.0 * keyhole_theta) / float(keyhole_arc_segments)
    keyhole_x_join = (
        keyhole_hole_radius * keyhole_hole_radius
        - keyhole_hole_tab_half_width * keyhole_hole_tab_half_width
    ) ** 0.5
    keyhole_front_x = keyhole_hole_radius + keyhole_hole_tab_length
    keyhole_tab_side_length = keyhole_front_x - keyhole_x_join
    keyhole_tab_front_length = 2.0 * keyhole_hole_tab_half_width
    tight_yaw_keyhole_theta = asin(
        max(
            -1.0,
            min(1.0, tight_yaw_keyhole_hole_tab_half_width / tight_yaw_keyhole_hole_radius),
        )
    )
    tight_yaw_keyhole_arc_delta = (
        2.0 * pi - 2.0 * tight_yaw_keyhole_theta
    ) / float(keyhole_arc_segments)
    tight_yaw_keyhole_x_join = (
        tight_yaw_keyhole_hole_radius * tight_yaw_keyhole_hole_radius
        - tight_yaw_keyhole_hole_tab_half_width * tight_yaw_keyhole_hole_tab_half_width
    ) ** 0.5
    tight_yaw_keyhole_front_x = (
        tight_yaw_keyhole_hole_radius + tight_yaw_keyhole_hole_tab_length
    )
    tight_yaw_keyhole_tab_side_length = (
        tight_yaw_keyhole_front_x - tight_yaw_keyhole_x_join
    )
    tight_yaw_keyhole_tab_front_length = 2.0 * tight_yaw_keyhole_hole_tab_half_width

    # Nominal v2 mesh fixtures start fixed-size. Runtime size randomization can
    # be added later by generating a small library of size buckets or by scaling
    # mesh geoms after collision validation.
    specs = {
        "true_hex_wall_mesh.obj": (hex_apothem, 6),
        "true_triangle_wall_mesh.obj": (triangle_apothem, 3),
    }
    for filename, (apothem, sides) in specs.items():
        side_length = regular_polygon_side_length(apothem=apothem, sides=sides)
        miter_extension = wall_thickness * tan(pi / sides)
        write_prism_mesh(
            output_dir / filename,
            side_length=side_length,
            miter_extension=miter_extension,
            thickness=wall_thickness,
            half_height=half_height,
        )

    tight_yaw_specs = {
        "true_hex_wall_tight_yaw_mesh.obj": (tight_yaw_hex_apothem, 6),
        "true_triangle_wall_tight_yaw_mesh.obj": (tight_yaw_triangle_apothem, 3),
    }
    for filename, (apothem, sides) in tight_yaw_specs.items():
        side_length = regular_polygon_side_length(apothem=apothem, sides=sides)
        miter_extension = wall_thickness * tan(pi / sides)
        write_prism_mesh(
            output_dir / filename,
            side_length=side_length,
            miter_extension=miter_extension,
            thickness=wall_thickness,
            half_height=half_height,
        )

    write_ring_mesh(
        output_dir / "true_hex_fixture_visual_mesh.obj",
        inner_points=regular_polygon_points(apothem=hex_apothem, sides=6),
        outer_points=regular_polygon_points(apothem=hex_apothem + wall_thickness, sides=6),
        half_height=half_height,
    )
    write_ring_mesh(
        output_dir / "true_triangle_fixture_visual_mesh.obj",
        inner_points=regular_polygon_points(apothem=triangle_apothem, sides=3),
        outer_points=regular_polygon_points(apothem=triangle_apothem + wall_thickness, sides=3),
        half_height=half_height,
    )
    write_ring_mesh(
        output_dir / "true_hex_fixture_visual_tight_yaw_mesh.obj",
        inner_points=regular_polygon_points(apothem=tight_yaw_hex_apothem, sides=6),
        outer_points=regular_polygon_points(
            apothem=tight_yaw_hex_apothem + wall_thickness,
            sides=6,
        ),
        half_height=half_height,
    )
    write_ring_mesh(
        output_dir / "true_triangle_fixture_visual_tight_yaw_mesh.obj",
        inner_points=regular_polygon_points(apothem=tight_yaw_triangle_apothem, sides=3),
        outer_points=regular_polygon_points(
            apothem=tight_yaw_triangle_apothem + wall_thickness,
            sides=3,
        ),
        half_height=half_height,
    )

    peg_tip_half_height = 0.00025
    peg_hex_points = regular_polygon_points(apothem=peg_hex_apothem, sides=6)
    peg_triangle_points = regular_polygon_points(apothem=peg_triangle_apothem, sides=3)
    peg_keyhole_points = keyhole_points(
        radius=keyhole_peg_radius,
        tab_half_width=keyhole_peg_tab_half_width,
        tab_length=keyhole_peg_tab_length,
        arc_segments=keyhole_arc_segments,
    )
    write_extruded_polygon_mesh(
        output_dir / "peg_hex_tip_cap_visual_mesh.obj",
        points=peg_hex_points,
        half_length=peg_tip_half_height,
    )
    write_ring_mesh(
        output_dir / "peg_hex_tip_outline_visual_mesh.obj",
        inner_points=scaled_points(peg_hex_points, 0.86),
        outer_points=peg_hex_points,
        half_height=peg_tip_half_height,
    )
    write_vertical_edge_highlight_mesh(
        output_dir / "peg_hex_side_edge_visual_mesh.obj",
        points=peg_hex_points,
        half_length=0.0545,
        radial_offset=0.00018,
        tangent_half_width=0.00028,
        radial_half_width=0.00008,
    )
    write_extruded_polygon_mesh(
        output_dir / "peg_triangle_tip_cap_visual_mesh.obj",
        points=peg_triangle_points,
        half_length=peg_tip_half_height,
    )
    write_ring_mesh(
        output_dir / "peg_triangle_tip_outline_visual_mesh.obj",
        inner_points=scaled_points(peg_triangle_points, 0.82),
        outer_points=peg_triangle_points,
        half_height=peg_tip_half_height,
    )
    write_vertical_edge_highlight_mesh(
        output_dir / "peg_triangle_side_edge_visual_mesh.obj",
        points=peg_triangle_points,
        half_length=0.0545,
        radial_offset=0.00018,
        tangent_half_width=0.00032,
        radial_half_width=0.00008,
    )
    write_extruded_polygon_mesh(
        output_dir / "peg_keyhole_tip_cap_visual_mesh.obj",
        points=peg_keyhole_points,
        half_length=peg_tip_half_height,
    )
    write_ring_mesh(
        output_dir / "peg_keyhole_tip_outline_visual_mesh.obj",
        inner_points=scaled_points(peg_keyhole_points, 0.84),
        outer_points=peg_keyhole_points,
        half_height=peg_tip_half_height,
    )

    slot_miter_extension = wall_thickness * tan(0.5 * slot_arc_delta)
    write_prism_mesh(
        output_dir / "true_slot_side_wall_mesh.obj",
        side_length=2.0 * (slot_half_x - slot_radius),
        miter_extension=slot_miter_extension,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_slot_arc_wall_mesh.obj",
        side_length=2.0 * slot_radius * sin(0.5 * slot_arc_delta),
        miter_extension=slot_miter_extension,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_extruded_polygon_mesh(
        output_dir / "peg_slot_mesh.obj",
        points=stadium_points(
            half_x=0.012 * 2.2,
            radius=0.012,
            arc_segments_per_end=6,
        ),
        half_length=0.055,
    )
    write_ring_mesh(
        output_dir / "true_slot_fixture_visual_mesh.obj",
        inner_points=stadium_points(
            half_x=slot_half_x,
            radius=slot_radius,
            arc_segments_per_end=8,
        ),
        outer_points=stadium_points(
            half_x=slot_half_x + wall_thickness,
            radius=slot_radius + wall_thickness,
            arc_segments_per_end=8,
        ),
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_tab_side_wall_mesh.obj",
        side_length=keyhole_tab_side_length,
        miter_extension=wall_thickness,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_tab_front_wall_mesh.obj",
        side_length=keyhole_tab_front_length,
        miter_extension=wall_thickness,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_arc_wall_mesh.obj",
        side_length=2.0 * keyhole_hole_radius * sin(0.5 * keyhole_arc_delta),
        miter_extension=wall_thickness * tan(0.5 * keyhole_arc_delta),
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_extruded_polygon_mesh(
        output_dir / "peg_keyhole_mesh.obj",
        points=peg_keyhole_points,
        half_length=0.055,
    )
    write_ring_mesh(
        output_dir / "true_keyhole_fixture_visual_mesh.obj",
        inner_points=keyhole_points(
            radius=keyhole_hole_radius,
            tab_half_width=keyhole_hole_tab_half_width,
            tab_length=keyhole_hole_tab_length,
            arc_segments=keyhole_arc_segments,
        ),
        outer_points=keyhole_points(
            radius=keyhole_hole_radius + wall_thickness,
            tab_half_width=keyhole_hole_tab_half_width + wall_thickness,
            tab_length=keyhole_hole_tab_length,
            arc_segments=keyhole_arc_segments,
        ),
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_tab_side_tight_yaw_mesh.obj",
        side_length=tight_yaw_keyhole_tab_side_length,
        miter_extension=wall_thickness,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_tab_front_tight_yaw_mesh.obj",
        side_length=tight_yaw_keyhole_tab_front_length,
        miter_extension=wall_thickness,
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_prism_mesh(
        output_dir / "true_keyhole_arc_tight_yaw_mesh.obj",
        side_length=2.0
        * tight_yaw_keyhole_hole_radius
        * sin(0.5 * tight_yaw_keyhole_arc_delta),
        miter_extension=wall_thickness * tan(0.5 * tight_yaw_keyhole_arc_delta),
        thickness=wall_thickness,
        half_height=half_height,
    )
    write_ring_mesh(
        output_dir / "true_keyhole_fixture_visual_tight_yaw_mesh.obj",
        inner_points=keyhole_points(
            radius=tight_yaw_keyhole_hole_radius,
            tab_half_width=tight_yaw_keyhole_hole_tab_half_width,
            tab_length=tight_yaw_keyhole_hole_tab_length,
            arc_segments=keyhole_arc_segments,
        ),
        outer_points=keyhole_points(
            radius=tight_yaw_keyhole_hole_radius + wall_thickness,
            tab_half_width=tight_yaw_keyhole_hole_tab_half_width + wall_thickness,
            tab_length=tight_yaw_keyhole_hole_tab_length,
            arc_segments=keyhole_arc_segments,
        ),
        half_height=half_height,
    )


if __name__ == "__main__":
    main()
